"$schema" = "https://starship.rs/config─schema.json"

format = """\
([\\[](bold yellow)$username$hostname[\\]](bold yellow) [─](fg:#232323) )\
$time\
$directory\
([─](fg:#232323) $cmd_duration)\
$fill\
( $git_state$git_branch)\
$line_break\
$character"""

add_newline = true
continuation_prompt = '... '

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[cmd_duration]
format = "took [$duration]($style)"

[directory]
truncation_length = 0
truncate_to_repo = false
style = 'bold cyan'
read_only = '\[RO\]'
read_only_style = 'bold red'

[fill]
symbol = '─'
style = 'fg:#232323'

[git_branch]
symbol = ''
format = '[$symbol $branch(:$remote_branch)]($style)'
style = 'bold green'

[git_state]
format = ' \([$state( $progress_current/$progress_total)]($style)\)'

[hostname]
ssh_only = true
style = "bold yellow"
format = '[@$hostname]($style)'

[time]
disabled = true

[username]
style_root = 'bold red'
style_user = 'bold yellow'
format = '[$user]($style)'
show_always = false
