-- stylua: ignore
local colors = {
	dark_1  = '#00005f',
	dark_2  = '#13181f',
	dark_3  = '#273143',
	-- dark_4  = '#2c323d',
	-- dark_4  = '#273143',
	-- dark_4 = '#39455b',
	dark_4 = '#556177',
	green   = '#c5f467',
	red     = '#ff8484',
	yellow  = '#ffcc5c',
	blue    = '#5cb2ff',
	white   = '#ffffff',
	inactive= '#504945',
}
	-- black        = '#282828',
	-- white        = '#ebdbb2',
	-- red          = '#fb4934',
	-- green        = '#b8bb26',
	-- blue         = '#83a598',
	-- yellow       = '#fe8019',
	-- gray         = '#a89984',
	-- darkgray     = '#3c3836',
	-- lightgray    = '#504945',
	-- inactivegray = '#7c6f64',

return {
	-- normal = {
	-- 	a = { bg = colors.green, fg = colors.dark_1, gui = 'bold' },
	-- 	b = { bg = colors.dark_3, fg = colors.white },
	-- 	c = { bg = colors.dark_2, fg = colors.white },
	-- 	x = { bg = colors.dark_2, fg = colors.white },
	-- 	y = { bg = colors.dark_2, fg = colors.white },
	-- 	z = { bg = colors.dark_3, fg = colors.white },
	-- },
	-- insert = {
	-- 	a = { bg = colors.blue, fg = colors.dark_1, gui = 'bold' },
	-- 	b = { bg = colors.dark_3, fg = colors.white },
	-- 	c = { bg = colors.dark_2, fg = colors.white },
	-- 	x = { bg = colors.dark_2, fg = colors.white },
	-- 	y = { bg = colors.dark_2, fg = colors.white },
	-- 	z = { bg = colors.dark_3, fg = colors.white },
	-- },
	-- visual = {
	-- 	a = { bg = colors.yellow, fg = colors.dark_1, gui = 'bold' },
	-- 	b = { bg = colors.dark_3, fg = colors.white },
	-- 	c = { bg = colors.dark_2, fg = colors.white },
	-- 	x = { bg = colors.dark_2, fg = colors.white },
	-- 	y = { bg = colors.dark_2, fg = colors.white },
	-- 	z = { bg = colors.dark_3, fg = colors.white },
	-- },
	-- replace = {
	-- 	a = { bg = colors.red, fg = colors.dark_1, gui = 'bold' },
	-- 	b = { bg = colors.dark_3, fg = colors.white },
	-- 	c = { bg = colors.dark_2, fg = colors.white },
	-- 	x = { bg = colors.dark_2, fg = colors.white },
	-- 	y = { bg = colors.dark_2, fg = colors.white },
	-- 	z = { bg = colors.dark_3, fg = colors.white },
	-- },
	-- command = {
	-- 	a = { bg = colors.green, fg = colors.dark_1, gui = 'bold' },
	-- 	b = { bg = colors.dark_3, fg = colors.white },
	-- 	c = { bg = colors.dark_2, fg = colors.white },
	-- 	x = { bg = colors.dark_2, fg = colors.white },
	-- 	y = { bg = colors.dark_2, fg = colors.white },
	-- 	z = { bg = colors.dark_3, fg = colors.white },
	-- },
	normal = {
		a = { bg = colors.green, fg = colors.dark_1, gui = 'bold' },
		b = { bg = colors.dark_4, fg = colors.white },
		c = { bg = colors.dark_4, fg = colors.white },
		x = { bg = colors.dark_4, fg = colors.white },
		y = { bg = colors.dark_4, fg = colors.white },
		z = { bg = colors.dark_4, fg = colors.white },
	},
	insert = {
		a = { bg = colors.blue, fg = colors.dark_1, gui = 'bold' },
		b = { bg = colors.dark_4, fg = colors.white },
		c = { bg = colors.dark_4, fg = colors.white },
		x = { bg = colors.dark_4, fg = colors.white },
		y = { bg = colors.dark_4, fg = colors.white },
		z = { bg = colors.dark_4, fg = colors.white },
	},
	visual = {
		a = { bg = colors.yellow, fg = colors.dark_1, gui = 'bold' },
		b = { bg = colors.dark_4, fg = colors.white },
		c = { bg = colors.dark_4, fg = colors.white },
		x = { bg = colors.dark_4, fg = colors.white },
		y = { bg = colors.dark_4, fg = colors.white },
		z = { bg = colors.dark_4, fg = colors.white },
	},
	replace = {
		a = { bg = colors.red, fg = colors.dark_1, gui = 'bold' },
		b = { bg = colors.dark_4, fg = colors.white },
		c = { bg = colors.dark_4, fg = colors.white },
		x = { bg = colors.dark_4, fg = colors.white },
		y = { bg = colors.dark_4, fg = colors.white },
		z = { bg = colors.dark_4, fg = colors.white },
	},
	command = {
		a = { bg = colors.green, fg = colors.dark_1, gui = 'bold' },
		b = { bg = colors.dark_4, fg = colors.white },
		c = { bg = colors.dark_4, fg = colors.white },
		x = { bg = colors.dark_4, fg = colors.white },
		y = { bg = colors.dark_4, fg = colors.white },
		z = { bg = colors.dark_4, fg = colors.white },
	},
	inactive = {
		a = { bg = colors.dark_4, fg = colors.white, gui = 'bold' },
		b = { bg = colors.dark_4, fg = colors.white },
		c = { bg = colors.dark_4, fg = colors.white },
		x = { bg = colors.dark_4, fg = colors.white },
		y = { bg = colors.dark_4, fg = colors.white },
		z = { bg = colors.dark_4, fg = colors.white },
	},
}
