#! /bin/sh

###############################################################################
# INIT                                                                        #
###############################################################################
xrandr --output DP-4 --mode 2560x1440 --primary --output DP-2 --mode 1920x1080 --left-of DP-4 &
sxhkd &
picom &
nitrogen --restore &
./.config/bspwmlaunch.sh &

# DP-2 connected 1920x1080+2560+0 (normal left inverted right x axis y axis) 509mm x 286mm
#    1920x1080     60.00*+
#    1680x1050     59.95
#    1600x900      60.00
#    1440x900      59.89
#    1280x1024     60.02
#    1280x800      59.81
#    1280x720      60.00
#    1024x768      60.00
#    800x600       60.32
#    640x480       59.94
# DP-3 disconnected (normal left inverted right x axis y axis)
# DP-4 connected 2560x1440+0+0 (normal le

#### CONFIG ####

bspc monitor DP-4 -d 1 2 3 4 5 6 7 8 9 0
bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width	2
bspc config window_gap		6
bspc config top_padding		0
bspc config -m DP-4 top_padding		30
bspc config bottom_padding	0
bspc config left_padding	0
bspc config right_padding	0

bspc config single_monocle	false
bspc config borderless_monocle	true
bspc config gapless_monocle true
bspc config click_to_focus true
bspc config gapless_monocle	false
#bspc config focus_by_distance	false
#bspc config focus_follows_pointer	false
#bspc config history_aware_focus	true
bspc config pointer_action1	move
bspc config pointer_action2	resize_side
bspc config pointer_action3	resize_corner
bspc config remove_disabled_monitors	true
bspc config merge_overlapping_monitors	true
bspc config split_ratio		0.50

bspc config pointer_modifier	mod4

###############################################################################
# COLORS                                                                      #
###############################################################################
bspc config normal_border_color "#262939"	# Unfocused
bspc config active_border_color "#1e1e1e"	# Focused window of unfocused monitor
bspc config focused_border_color "#5e81ac" 	# Focused window of focused monitor
bspc config presel_feedback_color "#5e81ac"	# Color of the node preselect area
#bspc config urgent_border_color "#dd2727"	# 
#bspc config focused_private_border_color "#000000"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-2)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-4)


###############################################################################
# RULES                                                                       #
###############################################################################
#bspc rule -a Chromium desktop='^2'
#bspc rule -a Kupfer.py focus=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a feh state=floating
#bspc rule -a Qalculate state=floating
#bspc rule -a Firefox state=floating
bspc rule -a File-roller state=floating


###############################################################################
# MARKED NODE BORDER COLOR HACK                                               #
###############################################################################
# This allows marked nodes to have their own border color

# CURRENT DOES NOT WORK
# MISSING XCB AND WMUTILS

#: "${MARKED_NORMAL_BCOLOR:=0x0000ff}"
#: "${MARKED_ACTIVE_BCOLOR:=0x00ff00}"
#: "${MARKED_FOCUSED_BCOLOR:=0xff0000}"
#
#while bspc subscribe -c 1 node_focus node_flag > /dev/null; do
#	bspc config focused_border_color "$(bspc config focused_border_color)"
#
#	bspc query -N -n '.marked.!focused.window' | while read -r wid; do
#		chwb -c "$MARKED_NORMAL_BCOLOR" "$wid"
#	done
#	bspc query -N -n '.marked.active.!focused.window' | while read -r wid; do
#		chwb -c "$MARKED_ACTIVE_BCOLOR" "$wid"
#	done
#	bspc query -N -n 'focused.marked' | while read -r wid; do
#		chwb -c "$MARKED_FOCUSED_BCOLOR" "$wid"
#	done
#done
