#+TITLE: My Config
#+AUTHOR: W. Riddle
#+DESCRIPTION: My Emacs config.
#+STARTUP: showeverything
#+PROPERTY: header-args :tangle yes

* TOC :toc_3: 
- [[#current-issues][Current Issues]]
- [[#setup][Setup]]
  - [[#lexical-binding][Lexical Binding]]
  - [[#disable-gc][Disable GC]]
  - [[#disable-native-compilation][Disable native compilation]]
  - [[#disable-gui-elements][Disable GUI elements]]
  - [[#set-default-window-size][Set default window size]]
  - [[#package-manager][Package Manager]]
  - [[#useful-debugging][Useful debugging]]
- [[#settings--variables][Settings / Variables]]
  - [[#backup-files-directory][Backup files directory]]
  - [[#utf-8][UTF-8]]
  - [[#fonts][Fonts]]
  - [[#os-specific][OS Specific]]
  - [[#line-numbers-and-line-behavior][Line Numbers and Line Behavior]]
  - [[#whitespace][Whitespace]]
  - [[#y-or-n-instead-of-yes-or-no][Y-or-N instead of Yes-or-No]]
  - [[#skip-special-buffers][Skip Special Buffers]]
  - [[#dired-settings][Dired Settings]]
- [[#custom-functions][Custom Functions]]
  - [[#reset-font-zoom][Reset font zoom]]
  - [[#open-config-file][Open config file]]
  - [[#tangle-and-reload-config-file][Tangle and reload config file]]
  - [[#add-trailing-space-to-all-headings-in-org-mode][Add trailing space to all headings in org mode]]
- [[#packages--after-hooks][Packages / After Hooks]]
  - [[#themes][Themes]]
    - [[#ef-themes][EF Themes]]
  - [[#evil][Evil]]
  - [[#general][General]]
  - [[#disabled-which-key][(DISABLED) Which-Key]]
  - [[#nerd-icons][Nerd Icons]]
  - [[#org-mode][Org Mode]]
    - [[#variable-pitch-org-old][Variable Pitch Org (OLD)]]
    - [[#toc-org][toc-org]]
    - [[#org-modern][Org Modern]]
    - [[#org-appear][Org Appear]]
    - [[#org-contrib][Org Contrib]]
    - [[#plantuml][PlantUML]]
  - [[#ultra-scroll-smooth-scrolling][Ultra-scroll (smooth scrolling)]]
  - [[#expand-region][Expand Region]]
  - [[#sudo-edit][Sudo Edit]]
  - [[#hydra][Hydra]]
  - [[#magit][Magit]]
  - [[#lsp][LSP]]
  - [[#packages-to-install][Packages to install]]
- [[#keybinds][Keybinds]]
- [[#other-hooks][Other Hooks]]
  - [[#disabled-prog-mode-line-numbers][(DISABLED) Prog Mode Line Numbers]]
  - [[#show-startup-time][Show startup time]]
- [[#misc][Misc]]
  - [[#disabled-emacs-server][(DISABLED) Emacs Server]]
- [[#helpful-links][Helpful Links]]

* Current Issues 

- ~pixel-scroll-precision-mode~ does not work correctly with a mouse and still skips over large images. ~ultra-scroll~ did not fix it. It will only work if the window is resized at least once after opening emacs. This issue does not occur using the trackpad.


* Setup 


** Lexical Binding 

This needs to be the first line

#+BEGIN_SRC emacs-lisp :tangle "~/.config/emacs/early-init.el"
;; -*- lexical-binding: t; -*-
#+END_SRC

#+BEGIN_SRC emacs-lisp
;; -*- lexical-binding: t; -*-
#+END_SRC


** Disable GC 

Disable GC to make startup faster. This *MUST* be re-enabled at the end, or else it will cause issues like freezing (the ~add-hook~ takes care of this for us).

The hook also ensures that it will run even if the config causes an error.

#+BEGIN_SRC emacs-lisp :tangle "~/.config/emacs/early-init.el"
  ;; Increase GC threshold during startup
  (setq gc-cons-threshold most-positive-fixnum)

  ;; Restore to a sane default after startup (will work if config errors out)
  (add-hook 'emacs-startup-hook
    	  (lambda ()
    	    (setq gc-cons-threshold 1600000)))
#+END_SRC


** Disable native compilation 

Disable native compilation because GCC is not installed.

#+BEGIN_SRC emacs-lisp :tangle "~/.config/emacs/early-init.el"
  ;;(setq package-native-compile nil)
  ;;(setq native-comp-deferred-compilation nil)
  ;;(setq native-comp-jit-compilation nil)
#+END_SRC


** Disable GUI elements 

#+BEGIN_SRC emacs-lisp :tangle "~/.config/emacs/early-init.el"
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)

  (setq inhibit-startup-screen t)
#+END_SRC


** Set default window size 

#+BEGIN_SRC emacs-lisp :tangle "~/.config/emacs/early-init.el"
  (setq default-frame-alist
        (append default-frame-alist
  	      '((left . 0)
  		(top . 0)
  		(width . 180)
  		(height . 50))))
#+END_SRC


** Package Manager 

Rather than install a package manager, I want to see if the default ~use-package~ along with the ~:vc~ tag for GitHub / specific commits or branches will be enough for me.

#+BEGIN_SRC emacs-lisp

  ;; Load any packages in ~/.config/emacs/lisp
  (add-to-list 'load-path
    	     (expand-file-name "lisp" user-emacs-directory))

  ;; GNU and NonGNU repositories are enabled by default, so no need to specify.
  (setq package-archives
    	     '(("melpa" . "https://melpa.org/packages/")
    	       ("gnu" . "https://elpa.gnu.org/packages/")
    	       ("nongnu" . "https://elpa.nongnu.org/nongnu/")))

  (package-initialize)

  (when (not package-archive-contents)
    (package-refresh-contents))


  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (require 'use-package)

  ;; Always install if nto installed.
  (setq use-package-always-ensure t)


#+END_SRC


** Useful debugging 

Enable to turn on debugging if you get unhelpful messages like
=Error (use-package): Cannot load x=.

#+BEGIN_SRC emacs-lisp
  ;; (toggle-debug-on-error)
  (setq use-package-verbose t
        use-package-expand-minimally nil)
#+END_SRC


* Settings / Variables 

#+BEGIN_SRC emacs-lisp
  (electric-pair-mode t)
  (electric-indent-mode 1)
  (show-paren-mode 1)
  (save-place-mode t)
  (savehist-mode t)
  (recentf-mode t)
  (setq recentf-max-menu-items 25)
  (setq recentf-max-saved-items 100)
  (global-auto-revert-mode t)
  (setq completions-format 'vertical)
  (blink-cursor-mode 0)
  (setq fill-column 80)
  (setq display-fill-column-indicator-column 80)
  (setq ring-bell-function 'ignore)
  (column-number-mode 1) ;; show column # in modeline
  (pixel-scroll-precision-mode) ;; should allow smooth scrolling over images in org mode
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (setq uniquify-buffer-name-style 'forward
        window-resize-pixelwise t
        frame-resize-pixelwise t
        load-prefer-newer t
        backup-by-copying t
        global-auto-revert-non-file-buffers t ;; auto revert dired and ibuffer
        kill-do-not-save-duplicates t
        custom-file (expand-file-name "custom.el" user-emacs-directory))
#+END_SRC


Delete selection when typing after selecting text.

#+begin_src emacs-lisp
  (delete-selection-mode 1)
#+end_src


Show column indicator for certain modes.

#+begin_src emacs-lisp
    (dolist (mode '(prog-mode-hook))
      (add-hook mode (lambda ()
    		   (display-fill-column-indicator-mode t))))
#+end_src


Word wrap only wraps at space by default. We could use ~toggle-truncate-lines~ instead of ~visual-line-mode~, but I don't like it wrapping at /any/ character. So instead, I'll modify it to also wrap by things such as slashes (for URLs).

#+begin_src emacs-lisp
  (setq word-wrap-by-category t)
  (modify-category-entry ?/ ?| (standard-category-table))
#+end_src


** Backup files directory 

This prevents emacs from spamming files with tildes everywhere, like =~init.el=.

#+BEGIN_SRC emacs-lisp
  (let ((backup-dir "/tmp/emacs/backups")
        (auto-saves-dir "/tmp/emacs/auto-saves"))
    (dolist (dir (list backup-dir auto-saves-dir))
      (when (not (file-directory-p dir))
        (make-directory dir t)))
    (setq backup-directory-alist `(("." . ,backup-dir))
  	auto-save-file-name-transforms `((".*" ,auto-saves-dir t))
  	auto-save-list-file-prefix (concat auto-saves-dir ".saves-")
  	tramp-backup-directory-alist `((".*" . ,backup-dir))
  	tramp-auto-save-directory auto-saves-dir))

  (setq backup-by-copying t   ;; Don't delete hardlinks
        delete-old-versions t ;; Clean up backups
        version-control t     ;; Use version numbers on backups
        kept-new-versions 5   ;; Keep five new versions
        kept-old-versions 2)  ;; Keep two old versions
#+END_SRC


** UTF-8 

#+BEGIN_SRC emacs-lisp
  (set-language-environment "UTF-8")
  (prefer-coding-system 'utf-8)
  (set-default-coding-systems 'utf-8)
  (set-terminal-coding-system 'utf-8)
  (set-keyboard-coding-system 'utf-8)
  (setq default-buffer-file-coding-system 'utf-8)
#+END_SRC


** Fonts 

#+BEGIN_SRC emacs-lisp
  (setq
   ;; wr/font-mono "SFMono Nerd Font"
   wr/font-mono "JetBrainsMono Nerd Font"
   ;; wr/font-mono "Maple Mono Normal NL NF"
   wr/font-variable "SF Pro"
   wr/font-base-size 140

   ;; These need to be floating point in order for it to scale when
   ;; increasing / decreasing font size via keybinds.
   wr/font-mono-relative-size 1.0
   wr/font-variable-relative-size 1.0)

  (set-face-attribute 'default nil
  		    :font wr/font-mono
  		    :height wr/font-base-size
  		    :weight 'normal)
  (set-face-attribute 'variable-pitch nil
  		    :font wr/font-variable
  		    :height wr/font-variable-relative-size
  		    :weight 'normal)
  (set-face-attribute 'fixed-pitch nil
  		    :font wr/font-mono
  		    :height wr/font-mono-relative-size
  		    :weight 'normal)

  ;; This is needed for emacsclient apparently.
  (add-to-list 'default-frame-alist
  	     (cons 'font
  		   (format "%s-%d" wr/font-mono (/ wr/font-base-size 10))))

  (setq-default line-spacing nil)
#+END_SRC


** OS Specific 

#+BEGIN_SRC emacs-lisp
  (cond ((eq system-type 'darwin)
         ;; Mac
         (custom-set-variables
  	'(mac-command-modifier 'meta)
  	'(mac-option-modifier 'alt)
  	'(mac-right-option-modifier 'super))
         (bind-key "M-0" 'wr/text-scale-reset)
         (bind-key "M-+" 'text-scale-increase)
         (bind-key "M-=" 'text-scale-increase)
         (bind-key "M--" 'text-scale-decrease)
         (use-package exec-path-from-shell
  	   :config
  	   (exec-path-from-shell-initialize))
         )

        ((eq system-type 'windows-nt)
         ;; Windows
         )

        ((eq system-type 'gnu/linux)
         ;; Linux
         ))
#+END_SRC


** Line Numbers and Line Behavior 

#+BEGIN_SRC emacs-lisp
  (global-display-line-numbers-mode 1)
  (global-visual-line-mode t)
#+END_SRC


** Whitespace 

#+BEGIN_SRC emacs-lisp
(custom-set-variables '(show-trailing-whitespace nil)) ;; turns this off because it's annoying and sometimes I keep whitespacing in headings to make it look even
#+END_SRC


** Y-or-N instead of Yes-or-No 


#+begin_src emacs-lisp
  (fset 'yes-or-no-p 'y-or-n-p)
#+end_src


** Skip Special Buffers 

When navigationg using ~previous-buffer~ and ~next-buffer~, this skips the annoying special buffers like ~*Messages*~. Keeps ~*scratch*~ though.

#+begin_src emacs-lisp
  (setq switch-to-prev-buffer-skip-regexp '("\\*Messages\\*"
  					  "\\*Warnings\\*"
  					  "\\*Help\\*"
  					  "\\*Completions\\*"
  					  "\\*Compile-Log\\*"
  					  "\\*Ibuffer\\*"
  					  "\\*Native-compile-Log"))
#+end_src


** Dired Settings 

#+begin_src emacs-lisp
  ;; Stop dired from spawning so many buffers when navigating
  (setq dired-kill-when-opening-new-dired-buffer t)
#+end_src


* Custom Functions 

** Reset font zoom 

#+BEGIN_SRC emacs-lisp
  (defun wr/text-scale-reset ()
    (interactive)
    (text-scale-set 0))
#+END_SRC


** Open config file 

#+BEGIN_SRC emacs-lisp
  (defun wr/open-config-org ()
    (interactive)
    (find-file "~/.config/emacs/config.org"))
#+END_SRC


** Tangle and reload config file 

#+BEGIN_SRC emacs-lisp
  (defun wr/tangle-and-reload-config ()
    (interactive)
    (message "Tangling file %s" (expand-file-name "config.org" user-emacs-directory))
    (org-babel-tangle-file (expand-file-name "config.org" user-emacs-directory))
    (load-file (expand-file-name "config.el" user-emacs-directory)))
#+END_SRC


** Add trailing space to all headings in org mode 

The current theme looks better when there is a space at the end of all headings. This will add spaces to the end of all headings if there isn't already a space.

#+begin_src emacs-lisp
  (defun wr/org-add-trailing-space-to-headings ()
    "Ensures every org heading ends with a trailing space."
    (interactive)
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward "^\\*+ " nil t)
        (end-of-line)
        (unless (eq (char-before) ?\s)
  	(insert " ")))))
#+end_src


* Packages / After Hooks 

** Themes 

*** EF Themes 

#+BEGIN_SRC emacs-lisp
  (use-package ef-themes
    :vc (:url "https://github.com/protesilaos/ef-themes" :rev :newest)
    :init
    (ef-themes-take-over-modus-themes-mode 1)
    :config
    (setq modus-themes-italic-constructs nil)
    (modus-themes-load-theme 'ef-duo-light))
#+END_SRC


** Evil 

#+BEGIN_SRC emacs-lisp
  (use-package evil
    :demand t
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    (setq evil-vsplit-window-right t)
    (setq evil-split-window-below t)
    (setq evil-want-C-u-scroll t)
    (setq evil-want-C-i-jump t)
    (setq evil-want-C-w-delete nil)
    (setq evil-want-Y-yank-to-eol t)
    (setq evil-respect-visual-line-mode t)
    (setq evil-kill-on-visual-paste nil)
    ;; (setq evil-undo-system undo-tree) ;; or undo-fu
    :config
    (evil-mode 1))

  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init))
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (use-package evil-commentary
    :config
    (evil-commentary-mode))
#+END_SRC


** General 

#+BEGIN_SRC emacs-lisp
  (use-package general
    :config
    (general-evil-setup))
#+END_SRC


** (DISABLED) Which-Key 

Rather than having which-key pop up all the time, just use ~C-h~ to popup a keymap on the side. That way it's on-demand, rather that popping up constantly.

#+BEGIN_SRC emacs-lisp :tangle no
  ;; ISSUE: which-key is blocked by echo area at the bottom. I'm not sure why.
  ;; Hacky solution at https://discourse.doomemacs.org/t/echo-area-covers-bottom-of-which-key/3026/2
  ;; for Doom, haven't found a solution for vanilla.
  ;;
  ;; (defadvice! fix-which-key--show-popup (fn act-popup-dim)
  ;; :around #'which-key--show-popup
  ;; (let ((height (car act-popup-dim))
  ;;       (width  (cdr act-popup-dim)))
  ;;   (funcall fn (cons (+ height 1) width))))
  (use-package which-key
    :init
    (which-key-mode 1)
    :config
    (setq which-key-side-window-location 'bottom
  	which-key-sort-order #'which-key-key-order-alpha
  	which-key-sort-uppercase-first nil
  	which-key-add-column-padding 1
  	which-key-max-display-columns nil
  	which-key-min-display-lines 6
  	which-key-side-window-slot -10
  	which-key-side-window-max-height 0.25
  	which-key-idle-delay 0.8
  	which-key-max-description-length 30
  	which-key-allow-imprecise-window-fit t))
  	;;which-key-separator "  "))
#+END_SRC


** Nerd Icons 

#+BEGIN_SRC emacs-lisp
  (use-package nerd-icons)
#+END_SRC


** Org Mode 

See [[file:moderntest.org][moderntest.org]] for org modern / org mode styling tests.

#+BEGIN_SRC emacs-lisp
  (use-package org
    :after nerd-icons
    :custom
    (org-directory "~/org")
    (org-log-done 'time)
    (org-startup-indented t)
    (org-log-into-drawer t)
    (org-special-ctrl-a/e t)
    (org-special-ctrl-k t)
    (org-confirm-babel-evaluate t)
    (org-src-fontify-natively t)
    (org-src-tab-acts-natively t)
    (org-hide-emphasis-markers t)
    (prettify-symbols-unprettify-at-point 'right-edge)
    (org-fontify-done-headline nil)
    (org-fontify-whole-heading-line nil) ;; made the heading go across the whole line
    (org-cycle-separator-lines 1) ;; this ensures that collapsing all headings still keeps at least 1 space between headings
    (org-tags-column 0)
    ;; (org-list-indent-offset 2) ;; add a little extra indent to make it look good
    (org-list-indent-offset 0)
    (org-startup-with-inline-images t) ;; show inline images
    (x-underline-at-descent-line t)
    (org-todo-keywords '((sequence "TODO(t)"
   				 "NEXT(n!/!)"
   				 "WAITING(w@!/!)"
   				 "|"
   				 "DONE(d!)"
   				 "CANCELED(c@!)")
                         (sequence "INBOX(i)"
   				 "PROJECT(p)"
   				 "IDEA(I)"
   				 "NOTE(o)")))
    (org-todo-keyword-faces
     '(("INBOX" . "DarkOrchid1")
       ("PROJECT" . +org-todo-test)
       ("WAITING" :background "blue")))
    :custom-face
    ;;(org-done ((nil (:strike-through t :foreground "#808080"))))
    ;;(org-headline-done ((nil (:strike-through t :foreground "#808080"))))
    (org-document-title ((t (:height 1.1 :weight bold))))
    (org-level-1 ((t (:height 1.1 :weight bold :background "#F9D4A0" :foreground "#000000" :overline "#000000" :underline "#000000"))))
    (org-level-2 ((t (:height 1.1 :weight bold :background "#EDE4FC" :foreground "#000000" :overline "#000000" :underline "#000000"))))
    (org-level-3 ((t (:height 1.1 :weight bold :background "#FCE4C8" :foreground "#000000" :overline "#000000" :underline "#000000"))))
    (org-level-4 ((t (:height 1.1 :weight bold :background "#C8E0F0" :foreground "#000000" :overline "#000000" :underline "#000000"))))
    (org-level-5 ((t (:height 1.1 :weight bold :background "#FAD0B8" :foreground "#000000" :overline "#000000" :underline "#000000"))))
    (org-level-6 ((t (:height 1.1 :weight bold :background "#D4ECD4" :foreground "#000000" :overline "#000000" :underline "#000000"))))
    (org-level-7 ((t (:height 1.1 :weight bold :background "#F0C8E0" :foreground "#000000" :overline "#000000" :underline "#000000"))))
    (org-level-8 ((t (:height 1.1 :weight bold :background "#F5EAA0" :foreground "#000000" :overline "#000000" :underline "#000000"))))
    ;; (org-level-1 ((t (:height 1.1 :weight bold :background "#F9D4A0" :foreground "#000000" ))))
    ;; (org-level-2 ((t (:height 1.1 :weight bold :background "#EDE4FC" :foreground "#000000" ))))
    ;; (org-level-3 ((t (:height 1.1 :weight bold :background "#FCE4C8" :foreground "#000000" ))))
    ;; (org-level-4 ((t (:height 1.1 :weight bold :background "#C8E0F0" :foreground "#000000" ))))
    ;; (org-level-5 ((t (:height 1.1 :weight bold :background "#FAD0B8" :foreground "#000000" ))))
    ;; (org-level-6 ((t (:height 1.1 :weight bold :background "#D4ECD4" :foreground "#000000" ))))
    ;; (org-level-7 ((t (:height 1.1 :weight bold :background "#F0C8E0" :foreground "#000000" ))))
    ;; (org-level-8 ((t (:height 1.1 :weight bold :background "#F5EAA0" :foreground "#000000" ))))
    :hook
    (org-mode . (lambda ()
               	(set-fontset-font t 'symbol (font-spec :family "Symbols Nerd Font Mono") nil 'prepend)
               	(set-fontset-font "fontset-default" 'unicode '("Symbols Nerd Font Mono"))
               	(setq prettify-symbols-alist '(("[ ]" . "󰄱" )
   					       ("[X]" . "󰱒")
   					       ("[-]" . "󰛲")))
               	(prettify-symbols-mode)))
    :config
    (org-babel-do-load-languages
     'org-babel-load-languages
     '((ruby . t)
       (latex . t)
       (plantuml . t)
       (python . t)
       (shell . t)
       (dot . t)
       (org . t)))
    (add-to-list 'org-src-lang-modes '("plantuml" . plantuml))
    )

  ;; redisplay images after executing code blocks
  (add-hook 'org-babel-after-execute-hook 'org-redisplay-inline-images)

  (with-eval-after-load 'org
    (setq org-structure-template-alist
          '(("c" . "center")
            ("ex" . "export")
            ("ea" . "export ascii")
            ("eh" . "export html")
            ("el" . "export latex")
            ("E" . "example")
            ("q" . "quote")
            ("s" . "src")
            ("1" . "src emacs-lisp")
            ("2" . "src java")
            ("v" . "verse"))))
#+END_SRC



*** Variable Pitch Org (OLD) 

#+BEGIN_SRC emacs-lisp :tangle no
  (use-package mixed-pitch
    :hook
    (text-mode . mixed-pitch-mode))

  (use-package org
    :after nerd-icons
    :custom
    (org-directory "~/org")
    (org-log-done 'time)
    (org-startup-indented t)
    (org-log-into-drawer t)
    (org-special-ctrl-a/e t)
    (org-special-ctrl-k t)
    (org-confirm-babel-evaluate t)
    (org-src-fontify-natively t)
    (org-src-tab-acts-natively t)
    (org-hide-emphasis-markers t)
    (prettify-symbols-unprettify-at-point 'right-edge)
    (org-fontify-done-headline t)
    (org-fontify-whole-heading-line t)
    (org-tags-column 0)
    (org-list-indent-offset 2)
    (x-underline-at-descent-line t)
    (org-todo-keywords '((sequence "TODO(t)"
  				 "NEXT(n!/!)"
  				 "WAITING(w@!/!)"
  				 "|"
  				 "DONE(d!)"
  				 "CANCELED(c@!)")
                         (sequence "PROJECT(p)"
  				 "IDEA(i)"
  				 "NOTE(o)")))
    (org-todo-keyword-faces
     '(("AREA" . "DarkOrchid1")
       ("[AREA]" . "DarkOrchid1")))
    :custom-face
    ;; (org-indent ((nil (:inherit (org-hide fixed-pitch)))))
    (org-done ((nil (:strike-through t :foreground "#808080"))))
    (org-headline-done ((nil (:strike-through t :foreground "#808080"))))
    ;; (org-block ((nil (:inherit fixed-pitch))))
    ;; (org-block-begin-line ((nil (:inherit fixed-pitch))))
    ;; (org-block-end-line ((nil (:inherit fixed-pitch))))
    ;; (org-verbatim ((nil (:inherit fixed-pitch))))
    ;; (org-table ((nil (:inherit fixed-pitch))))
    ;; (org-meta-line ((nil (:inherit fixed-pitch))))
    ;; (org-special-keyword ((nil (:inherit fixed-pitch))))
    ;; (org-document-info ((nil (:inherit fixed-pitch))))
    ;; (org-document-info-keyword ((nil (:inherit fixed-pitch))))
    ;; (org-code ((nil (:inherit (shadow fixed-pitch)))))
    ;; (org-list-dt ((nil (:inherit fixed-pitch))))
    ;; (line-number ((nil (:inherit fixed-pitch))))
    ;; (line-number-current-line ((nil (:inherit fixed-pitch))))
    ;; (org-document-title ((t (:inherit variable-pitch :height 1.1 :weight bold))))
    ;; (org-level-1 ((t (:inherit variable-pitch :height 1.1 :weight bold))))
    ;; (org-level-2 ((t (:inherit variable-pitch :height 1.1 :weight bold))))
    ;; (org-level-3 ((t (:inherit variable-pitch :height 1.1 :weight bold))))
    ;; (org-level-4 ((t (:inherit variable-pitch :height 1.1 :weight bold))))
    ;; (org-level-5 ((t (:inherit variable-pitch :height 1.1 :weight bold))))
    ;; (org-level-6 ((t (:inherit variable-pitch :height 1.1 :weight bold))))
    ;; (org-level-7 ((t (:inherit variable-pitch :height 1.1 :weight bold))))
    (org-document-title ((t (:height 1.1 :weight bold))))
    (org-level-1 ((t (:height 1.1 :weight bold :background "#F9D4A0" :foreground "#000000" :overline "#000000" :underline "#000000"))))
    (org-level-2 ((t (:height 1.1 :weight bold :background "#EDE4FC" :foreground "#000000" :overline "#000000" :underline "#000000"))))
    (org-level-3 ((t (:height 1.1 :weight bold :background "#FCE4C8" :foreground "#000000" :overline "#000000" :underline "#000000"))))
    (org-level-4 ((t (:height 1.1 :weight bold :background "#C8E0F0" :foreground "#000000" :overline "#000000" :underline "#000000"))))
    (org-level-5 ((t (:height 1.1 :weight bold :background "#FAD0B8" :foreground "#000000" :overline "#000000" :underline "#000000"))))
    (org-level-6 ((t (:height 1.1 :weight bold :background "#D4ECD4" :foreground "#000000" :overline "#000000" :underline "#000000"))))
    (org-level-7 ((t (:height 1.1 :weight bold :background "#F0C8E0" :foreground "#000000" :overline "#000000" :underline "#000000"))))
    (org-level-8 ((t (:height 1.1 :weight bold :background "#F5EAA0" :foreground "#000000" :overline "#000000" :underline "#000000"))))
    :hook
    (org-mode . (lambda ()
              	(set-fontset-font t 'symbol (font-spec :family "Symbols Nerd Font Mono") nil 'prepend)
              	(set-fontset-font "fontset-default" 'unicode '("Symbols Nerd Font Mono"))
              	(setq prettify-symbols-alist '(("[ ]" . "󰄱" )
                                                 ("[X]" . "󰱒")
                                                 ("[-]" . "󰛲")))
              	(prettify-symbols-mode)
  		(org-toggle-pretty-entities 1))) ;; prettify some latex entities like ast{}, alpha{}, pi{}, euro{}, tilde{}, etc.
    :config
    (org-babel-do-load-languages
     'org-babel-load-languages
     '((ruby . t)
       (latex . t)
       (plantuml . t)
       (python . t)
       (shell . t)
       (dot . t)
       (org . t)))
    )


  (with-eval-after-load 'org
    (setq org-structure-template-alist
          '(("c" . "center")
            ("ex" . "export")
            ("ea" . "export ascii")
            ("eh" . "export html")
            ("el" . "export latex")
            ("E" . "example")
            ("q" . "quote")
            ("s" . "src")
            ("1" . "src emacs-lisp")
            ("2" . "src java")
            ("v" . "verse"))))
#+END_SRC


*** toc-org 

#+BEGIN_SRC emacs-lisp
  (use-package toc-org
    :commands toc-org-enable
    :init (add-hook 'org-mode-hook 'toc-org-enable))
#+END_SRC


*** Org Modern 

#+BEGIN_SRC emacs-lisp
  (defface wr/org-modern-todo-todo
    '((t :background "#FF9E9E" ;; red
         :foreground "#000000"
         :box (:line-width -1 :color "#000000")))
    "Todo todo face.")

  (defface wr/org-modern-todo-next
    '((t :background "gray90" ;; gray
         :foreground "#000000"
         :box (:line-width -1 :color "#000000")))
    "Next todo face.")

  (defface wr/org-modern-todo-waiting
    '((t :background "#FFAC63" ;; orange
         :foreground "#000000"
         :box (:line-width -1 :color "#000000")))
    "Waiting todo face.")

  (defface wr/org-modern-todo-done
    '((t :background "#9EFFB0" ;; green
         :foreground "#000000"
         :box (:line-width -1 :color "#000000")))
    "Done todo face.")

  (defface wr/org-modern-todo-canceled
    '((t :background "#C72626" ;; dark red
         :foreground "#FFFFFF"
         :box (:line-width -1 :color "#000000")))
    "Canceled todo face.")

  (defface wr/org-modern-todo-inbox
    '((t :background "gold" ;; yellow
         :foreground "#000000"
         :box (:line-width -1 :color "#000000")))
    "Inbox todo face.")

  (defface wr/org-modern-todo-project
    '((t :background "#D4BFFF" ;; purple
         :box (:line-width -1 :color "#000000")))
    "Project todo face.")

  (defface wr/org-modern-todo-idea
    '((t :background "#BFFFF6" ;; cyan
         :box (:line-width -1 :color "#000000")))
    "Idea todo face.")

  (defface wr/org-modern-todo-note
    '((t :background "#9ECDFF" ;; blue
         :box (:line-width -1 :color "#000000")))
    "Note todo face.")


  (use-package org-modern
    :custom
    (org-modern-label-border 0.1)
    (org-modern-star 'replace)
    ;;(org-modern-replace-stars "")
    (org-modern-replace-stars "     ")
    (org-modern-table-horizontal 3)
    (org-modern-checkbox '((?X . "󰱒")
  			 (?- . "󰛲")
  			 (?\s . "󰄱")))
    (org-modern-list '((?+ . "◦")
  		     (?- . "•")
  		     (?* . "•")))
    (org-modern-todo-faces
     '(("TODO" . wr/org-modern-todo-todo)
       ("NEXT" . wr/org-modern-todo-next)
       ("WAITING" . wr/org-modern-todo-waiting)
       ("DONE" . wr/org-modern-todo-done)
       ("CANCELED" . wr/org-modern-todo-canceled)
       ("INBOX" . wr/org-modern-todo-inbox)
       ("PROJECT" . wr/org-modern-todo-project)
       ("IDEA" . wr/org-modern-todo-idea)
       ("NOTE" . wr/org-modern-todo-note)))
    :custom-face
    (org-modern-label ((t (:inherit fixed-pitch :height 1.0 ))))
    :hook
    (org-mode . org-modern-mode))
#+END_SRC


*** Org Appear 

#+BEGIN_SRC emacs-lisp
  (use-package org-appear
    :vc (:url "https://github.com/awth13/org-appear" :rev :newest)
    :after org
    :hook
    (org-mode . org-appear-mode))
#+END_SRC


*** Org Contrib 

Add this so I can get ~ox-extras~ so that I can ~:ignore:~ headings I don't want to export.

#+begin_src emacs-lisp
  (use-package org-contrib
    :config
    (require 'ox-extra)
    (ox-extras-activate '(ignore-headlines)))
#+end_src


*** PlantUML 

#+begin_src emacs-lisp
  (setq org-plantuml-jar-path (expand-file-name "~/lsp/plantuml-1.2026.2.jar"))
#+end_src


** Ultra-scroll (smooth scrolling) 

#+BEGIN_SRC emacs-lisp
  (use-package ultra-scroll
    :vc (:url "https://github.com/jdtsmith/ultra-scroll" :rev :newest)
    :init
    (setq scroll-conservatively 3
          scroll-margin 0)
    :config
    (ultra-scroll-mode 1))
#+END_SRC


** Expand Region 

#+BEGIN_SRC emacs-lisp
  (use-package expand-region)
#+END_SRC


** Sudo Edit 

This is useful if we edit a file, only to find out we needed sudo privileges.

#+begin_src emacs-lisp
  (use-package sudo-edit)
#+end_src


** Hydra 


#+begin_src emacs-lisp
  (use-package hydra
    :after evil
    :defer t)

  (defun wr/evil-window-increase-width-five ()
    "Increase window width by 5"
    (interactive)
    (evil-window-increase-width 5))

  (defun wr/evil-window-decrease-width-five ()
    "Decrease window width by 5"
    (interactive)
    (evil-window-decrease-width 5))

  (defhydra hydra-window-resize ()
    "resize"
    ("<" wr/evil-window-decrease-width-five "-width")
    (">" wr/evil-window-increase-width-five "+width")
    ("-" evil-window-decrease-height "-height")
    ("_" evil-window-decrease-height "-height")
    ("+" evil-window-increase-height "+height")
    ("=" balance-windows "balance"))

  (dolist (key '("<" ">" "-" "_" "+" "="))
    (define-key evil-window-map (kbd key) 'hydra-window-resize/body))
#+end_src


** Magit 

#+begin_src emacs-lisp
  (use-package magit
    :defer t
    ;; :commands
    ;; (magit-status magit-get-current-branch)
    :custom
    ;; Open in the same window, not a different window
    ;;(magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1)
    ;; Show character level changes
    (magit-diff-refine-hunk 'all))
#+end_src


** TODO LSP 





** TODO Packages to install 

- Company / LSP
- Vertico
- Consult
- savehist?
- marginalia?
- swiper?
- flycheck?
- rainbow parens?
- neotree / treemacs?
- undo tree / undofu
- harpoon
- consult-xref-stack
- Bufler?
- dumb-jump? (not sure I need this yet)

- [X] Magit

- Go through old config in ~~/.config/emacs/old_config_todo/~
- how to mark buffers to delete?


* Keybinds 

Global prefix lets us access the leader key menu from insert / emacs mode.

#+BEGIN_SRC emacs-lisp
  (with-eval-after-load 'general
    (general-define-key
     :states '(normal visual)
     "}" 'next-buffer
     "{" 'previous-buffer
     "M-;" 'evil-commentary
     "C-=" 'er/expand-region)

    ;; s sneak

    (general-create-definer leader-keys
      :prefix "SPC"
      :global-prefix "C-S-SPC")

    (general-create-definer local-leader-keys
      :prefix "SPC m"
      :global-prefix "C-S-SPC m")

    (leader-keys
      :states '(normal visual insert emacs)
      :keymaps 'override

      ;; " list registers

      ;; / swiper

      ;; tab visit last file

      ;; a align
      ;; a e easyalign

      "b" '(:ignore t :wk "buffer")
      "b b" '(switch-to-buffer :wk identity)
      "b i" '(ibuffer :wk identity)
      "b d" '(kill-current-buffer :wk identity)
      "b D" '(kill-buffer :wk identity)
      "b n" '(next-buffer :wk identity)
      "b p" '(previous-buffer :wk identity)
      "b r" '(revert-buffer :wk "reload buffer")

      "B" '(:ignore t :wk "bookmarks TODO")
      ;; Bb/BB list bookmarks
      ;; Bg list global bookmarks? (bookmarks that are always saved in config.org?)
      ;; Bt toggle bookmark
      ;; Bx clear non-global bookmarks?
      ;; Ba annotate bookmark?
      ;; Bj move down?
      ;; Bk move up?
      ;; Bn next bookmark?
      ;; Bp previous bookmark?


      "d" '(:ignore t :wk "dired TODO")
      "d d" '(dired :wk identity)

      "e" '(:ignore t :wk "eval")
      "e b" '(eval-buffer :wk identity)
      "e d" '(eval-defun :wk identity)
      "e e" '(eval-expression :wk identity)
      "e l" '(eval-last-sexp :wk identity)
      "e r" '(eval-region :wk identity)
      "e c" '(wr/tangle-and-reload-config :wk identity)

      "f" '(:ignore t :wk "find")
      "f f" '(find-file :wk identity)
      "f r" '(recentf-open-files :wk "recent files")
      "f u" '(sudo-edit-find-file :wk identity)
      "f U" '(sudo-edit :wk identity)
      "f 1" '(wr/open-config-org :wk "open config.org")
      ;; f g grep/ripgrep/ag

      "g" '(:ignore t :wk "git TODO")
      "g s" '(magit-status :wk identity)
      "g l" '(magit-log :wk identity) ;; show branch commits by selecting "other (o)"
      "g f" '(magit-log-buffer-file :wk identity)
      "g b" '(magit-show-refs :wk "show branches")
      ;; gB blame?
      ;; gBl blame line?

      "h" '(:ignore t :wk "help")
      "h f" '(describe-function :wk identity)
      "h F" '(describe-face :wk identity)
      "h v" '(describe-variable :wk identity)
      "h k" '(describe-key :wk identity)
      "h K" '(describe-key :wk identity)

      ;; m marks

      "n" '(:ignore t :wk "treemacs/nerdtree TODO")
      ;; N treemacs/nerdtree current file

      "o" '(:ignore t :wk "org TODO")

      "p" '(:ignore t :wk "harpoon TODO")

      ;; s easymotion
      ;; S easymotion overwin

      "t" '(:ignore t :wk "terminal TODO")

      ;; u undo tree

      "w" '(:ignore t :wk "window")
      "w +" '(hydra-window-resize/body :wk "+height")
      "w -" '(hydra-window-resize/body :wk "-height")
      "w _" '(hydra-window-resize/body :wk "-height")
      "w <" '(hydra-window-resize/body :wk "-width")
      "w =" '(hydra-window-resize/body :wk "balance windows")
      "w >" '(hydra-window-resize/body :wk "+width")
      "w b" '(evil-window-bottom-right :wk identity)
      "w c" '(evil-window-delete :wk identity)
      "w d" '(evil-window-delete :wk identity)
      "w h" '(evil-window-left :wk identity)
      "w H" '(evil-window-move-far-left :wk identity)
      "w j" '(evil-window-down :wk identity)
      "w J" '(evil-window-move-very-bottom :wk identity)
      "w k" '(evil-window-up :wk identity)
      "w K" '(evil-window-move-very-top :wk identity)
      "w l" '(evil-window-right :wk identity)
      "w L" '(evil-window-move-far-right :wk identity)
      "w n" '(evil-window-new :wk identity)
      "w o" '(evil-window-other-windows :wk identity)
      "w p" '(evil-window-mru :wk identity)
      "w r" '(evil-window-rotate-downwards :wk identity)
      "w R" '(evil-window-rotate-upwards :wk identity)
      "w s" '(evil-window-split :wk identity)
      "w S" '(evil-window-split :wk identity)
      "w t" '(evil-window-top-left :wk identity)
      "w v" '(evil-window-vsplit :wk identity)
      "w w" '(evil-window-next :wk identity)
      "w W" '(evil-window-prev :wk identity)
      "w |" '(evil-window-set-width :wk identity)
      "w C-_" '(evil-window-set-height :wk identity)


      "." '(:ignore t :wk "multiple cursors TODO")
      ;; ./ select with regex
      ;; .. add cursor @ pos

      ";" '(:ignore t :wk "settings")
      "; l" '(display-line-numbers-mode :wk "toggle line numbers")
      "; RET" '(visual-line-mode :wk "toggle word wrap")
      ;; ;l toggle relative line numbers
      ;; ;L toggle line numbers
      ;; ;o toggle showing overlength (highlight characters past 80 char)
      ;; ;t +tabs/spaces
      ;; ;tt toggle between tabs and spaces
      ;; ;tc convert all to tabs / spaces
      ;; ;tw prompt for tab width
      ;; ;t1 set to 1 char tab width
      ;; ;t2 set to 1 char tab width
      ;; ;t3 set to 1 char tab width
      ;; ;t4 set to 1 char tab width
      ;; ;t8 set to 1 char tab width
      ;; ;w cycle between showing whitespace
      ;; ;SPC remove trailing spaces
      )


    (local-leader-keys
      :states '(normal visual insert emacs)
      :keymaps 'org-mode-map
      "#" '(org-insert-structure-template :wk "insert template")
      "y" '(org-store-link :wk identity)
      "p" '(org-insert-link :wk identity)))
#+END_SRC


* Other Hooks 


** (DISABLED) Prog Mode Line Numbers 

Display line numbers in programming modes. TODO: enable this for all modes? At least prog and org.

Currently disabled because we are using ~(global-display-line-numbers-mode 1)~.

#+BEGIN_SRC emacs-lisp :tangle no
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
#+END_SRC


** Show startup time 

#+BEGIN_SRC emacs-lisp
  (add-hook 'emacs-startup-hook
  	  (lambda ()
  	    (message "Emacs ready in %s with %d garbage collectios."
  		     (format "%.2f seconds"
  			     (float-time
  			      (time-subtract after-init-time before-init-time)))
  		     gcs-done)))
#+END_SRC


** Add trailing spaces to org mode headings on save 

#+begin_src emacs-lisp
  (add-hook 'org-mode-hook
          (lambda ()
            (add-hook 'before-save-hook
                      #'wr/org-add-trailing-space-to-headings
                      nil t)))
#+end_src


* Misc 


** (DISABLED) Emacs Server 

Use emacsclient to open files in an already-running Emacs process (TODO).

#+BEGIN_SRC emacs-lisp :tangle no
  (require 'server)
  (unless (server-running-p) (server-start))
#+END_SRC


* Helpful Links 

- https://sam217pa.github.io/2016/09/23/keybindings-strategies-in-emacs/
- https://github.com/zzamboni/dot-emacs/
- https://orgmode.org/worg/org-contrib/babel/examples/fontify-src-code-blocks.html
- https://github.com/minad/org-modern/blob/main/org-modern.el
